# Generated by Django 6.0 on 2026-08-23 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DamageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama Jenis")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Dibuat"
                    ),
                ),
            ],
            options={
                "verbose_name": "Jenis Kerusakan",
                "verbose_name_plural": "Jenis Kerusakan",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama Lokasi")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Dibuat"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lokasi",
                "verbose_name_plural": "Lokasi",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FacilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Nomor Laporan",
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("medium", "Sedang"),
                            ("high", "Tinggi"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Tingkat Urgensi",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Jelaskan kerusakan secara detail",
                        verbose_name="Keterangan",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="damage_photos/%Y/%m/%d/",
                        verbose_name="Foto Kerusakan",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Menunggu"),
                            ("repairing", "Sedang Diperbaiki"),
                            ("completed", "Selesai"),
                        ],
                        default="waiting",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority_score",
                    models.IntegerField(
                        default=1, editable=False, verbose_name="Skor Prioritas"
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Catatan Petugas"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Laporan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Tanggal Diperbarui"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                (
                    "damage_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="reports.damagetype",
                        verbose_name="Jenis Kerusakan",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pelapor",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="reports.location",
                        verbose_name="Lokasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laporan",
                "verbose_name_plural": "Laporan Kerusakan",
                "ordering": ["-priority_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RepairHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Menunggu"),
                            ("repairing", "Sedang Diperbaiki"),
                            ("completed", "Selesai"),
                        ],
                        max_length=10,
                        verbose_name="Status Sebelumnya",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Menunggu"),
                            ("repairing", "Sedang Diperbaiki"),
                            ("completed", "Selesai"),
                        ],
                        max_length=10,
                        verbose_name="Status Baru",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Catatan perubahan status",
                        null=True,
                        verbose_name="Catatan",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Perubahan"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repair_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diubah Oleh",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="reports.facilityreport",
                        verbose_name="Laporan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riwayat Perbaikan",
                "verbose_name_plural": "Riwayat Perbaikan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="facilityreport",
            index=models.Index(
                fields=["status", "priority_score"],
                name="reports_fac_status_6afaae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="facilityreport",
            index=models.Index(
                fields=["urgency", "status"], name="reports_fac_urgency_b550f5_idx"
            ),
        ),
    ]
